return {
  "nvim-treesitter/nvim-treesitter",
  branch = "master",
  lazy = false,
  build = ":TSUpdate",
  main = "nvim-treesitter.configs",
  opts = {
    ensure_installed = {
      "lua",
      "tsx",
      "typescript",
      "rust",
      "javascript",
      "html",
      "json",
      "yaml",
      "dockerfile",
      "markdown",
      "markdown_inline",
    },
    auto_install = true,
    highlight = { enable = true },
    indent = { enable = true },
  },
}
